#pragma kernel CSMain
#include "Voxels.hlsl"

StructuredBuffer<uint> uVoxels; // Readonly packed uint buffer
RWStructuredBuffer<uint> uIndirectArgs;
RWStructuredBuffer<GeometryData> uFeedback;
RWStructuredBuffer<ChunkFeedback> uChunkFeedback;

RWStructuredBuffer<uint> uRenderPrimitivesIndirectArgs;
RWStructuredBuffer<uint> uRenderPrimitivesIndexedArgs;

groupshared uint sVertexCount;
groupshared uint sIndexCount;

static const int3 Normals[] = { int3(0, 0, -1), int3(0, 0, 1), int3(0, 1, 0), int3(0, -1, 0), int3(-1, 0, 0), int3(1, 0, 0) };

bool hasVoxel(int3 coord) {
    int3 wSize = int3(uChunkGrid * uChunkSize);
    if (coord.x < 0 || coord.x >= wSize.x || coord.y < 0 || coord.y >= wSize.y || coord.z < 0 || coord.z >= wSize.z) {
        return false;
    }
    uint idx = to1D(coord);
    uint arrayIdx = idx / 32;
    uint bitIdx = idx % 32;
    return ((uVoxels[arrayIdx] >> bitIdx) & 1u) == 1u;
}

[numthreads(8, 8, 8)]
void CSMain (uint3 dispatchID : SV_DispatchThreadID, uint3 groupID : SV_GroupID, uint3 groupThreadID : SV_GroupThreadID)
{
    if (groupThreadID.x == 0 && groupThreadID.y == 0 && groupThreadID.z == 0) {
        sVertexCount = 0;
        sIndexCount = 0;
    }

    AllMemoryBarrierWithGroupSync();
    
    uint globalVoxelIndex = to1D(dispatchID);
    uint arrayIdx = globalVoxelIndex / 32;
    uint bitIdx = globalVoxelIndex % 32;

    if (((uVoxels[arrayIdx] >> bitIdx) & 1u) == 1u) {
        int3 coord = int3(dispatchID);

        uint vertexCount = 0;
        uint indexCount = 0;

        for (int i = 0; i < 6; i++)
        {
            if (!hasVoxel(coord + Normals[i])) 
            {
                vertexCount += 4;
                indexCount += 6;
            }
        }
        
        InterlockedAdd(sVertexCount, vertexCount);
        InterlockedAdd(sIndexCount, indexCount);
    }

    AllMemoryBarrierWithGroupSync();

    if (groupThreadID.x == 0 && groupThreadID.y == 0 && groupThreadID.z == 0)
    {
        uint vertexOffset = 0, indexOffset = 0;
    
        InterlockedAdd(uFeedback[0].vertexCount, sVertexCount, vertexOffset);
        InterlockedAdd(uFeedback[0].indexCount, sIndexCount, indexOffset);
    
        uint3 groupGrid = (uChunkGrid * uChunkSize) / 8;
        uint index = groupID.x + groupGrid.x * (groupID.y + groupGrid.y * groupID.z);

        uChunkFeedback[index].vertexOffset = vertexOffset;
        uChunkFeedback[index].vertexCount = sVertexCount;
        uChunkFeedback[index].indexOffset = indexOffset;
        uChunkFeedback[index].indexCount = sIndexCount;

        uIndirectArgs[0] = uFeedback[0].indexCount;
        uRenderPrimitivesIndirectArgs[0] = uFeedback[0].indexCount;
        uRenderPrimitivesIndirectArgs[1] = 1;

        uRenderPrimitivesIndexedArgs[0] = uFeedback[0].indexCount;
        uRenderPrimitivesIndexedArgs[1] = 1;
        uRenderPrimitivesIndexedArgs[2] = 0;
        uRenderPrimitivesIndexedArgs[3] = 0;
        uRenderPrimitivesIndexedArgs[4] = 0;
    }
}